import { PrismaClient } from "@prisma/client";

/**
 * Carga de empresas desde la base de asistentes de IT Now Live.
 * 720 empresas únicas, deduplicadas, con categoría inferida por reglas
 * (nombre + sector + dominio). Se cargan como proveedores potenciales
 * (active: true, verified: false), sin usuarios asociados — el matching
 * puede considerarlas, pero no pueden loguearse hasta reclamar cuenta.
 *
 * Idempotente: si la organización con el mismo nombre ya existe, la salta.
 * Uso: DATABASE_URL=... npm run load-companies
 */

const prisma = new PrismaClient();

interface CompanyRow {
  name: string;
  category: string;
  city: string;
  department: string | null;
}

const COMPANIES: CompanyRow[] = [
  { name: "4TO VICEMINISTERIO DE GOBERNACION", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "7TIMES", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "A.MELVILLE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "AATECHNOLOGY", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ABBOTT LABORATORIOS", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "ABC ALPHA", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "ABG", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "AC TALENTOS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ACEROS ARQUITECTONICOS", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "ACEROS DE GUATEMALA", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "ACOSA GUATEMALA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "ADISTTEC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ADISTEC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "AFRA SERVICES", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "AFTERNOON CAFE", category: "Hotelería y Turismo", city: "Guatemala City", department: "Guatemala" },
  { name: "AGEXPORT", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "AGROAMERICA", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "AKROS TECHNOLOGIES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ALCSA", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "ALDO SIBRIAN", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "ALEGALIS", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "ALFA COMUNICACIONES Y SERVICIOS", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "ALIMENTOS CORPORATIVOS CORALSA S.A", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "ALKEMY S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ALLMONI", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "ALMACENES Y SERVICIOS, S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ALMO", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ALOPSA", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "ALPISTORE", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "ALSICORP GT", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "ALTEC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "AMADEUS", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "AMCHAM GUATEMALA", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "AMPLIOS MERCADOS", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "AMTEK CENTROAMERICA, S.A.", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "AMVA", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "ANALYTECTS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ANFLO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ANTILLON", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "APDE ROBLE", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "APDE SOLALTO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "APEX", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "APEX (CBC)", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "APM TERMINALS", category: "Transporte", city: "Retalhuleu", department: "Retalhuleu" },
  { name: "APMTERMINALS QUETZAL S.A.", category: "Transporte", city: "Santa Rosa", department: "Santa Rosa" },
  { name: "APOLO", category: "Bienes Raíces", city: "Guatemala City", department: "Guatemala" },
  { name: "APPGATE", category: "Ciberseguridad", city: "Guatemala City", department: "Guatemala" },
  { name: "APPLIS GT", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "APPSYSTEMS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ARCESA", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "ARCHIPEL SYSTEMS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ARISTA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ARMESA", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ARROCESA LOS CORRALES, S.A", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "ASEDBIEN", category: "Hotelería y Turismo", city: "Guatemala City", department: "Guatemala" },
  { name: "ASEGURADORA GENERAL S.A", category: "Seguros", city: "Guatemala City", department: "Guatemala" },
  { name: "ASEGURO", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ASEGURO AGENCIA DE SEGUROS, S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ASEGUROS S.A.", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "ASESOR LEGAL Y FINANCIERO", category: "Legal", city: "Guatemala City", department: "Guatemala" },
  { name: "ASI ASISTENCIA INTERNACIONAL, S.A", category: "Seguros", city: "Guatemala City", department: "Guatemala" },
  { name: "ASIESTRATEGIAS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ASIM", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "ASOCIACION ESPAÑOLA DE BENEFICIENCIA", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "ASOCIACION EDUCATIVA ELIM", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "ASOCIACION FINTECH DE GUATEMALA", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ASTTEM", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ATA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ATELIER TALLER DE ESPACIOS", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "ATENTO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "AUTOMONO", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "AVAYA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "AW", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "AXENTO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "B&R INGENIERIA DE SISTEMAS, S. A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BAC", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "BAM", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "BANCO DE GUATEMALA", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BANCO DE LOS TRABAJADORES", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BANCO G&T", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BANCO G&T CONTINENTAL", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BANCO INDUSTRIAL", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BANCO INMOBILIARIO", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BANCO PROMERICA", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BANRURAL", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BANTRAB", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BARCELO HOTEL GROUP", category: "Hotelería y Turismo", city: "Guatemala City", department: "Guatemala" },
  { name: "BBDO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BC CONSULTING, S.A", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "BDG", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "BEAUTY LINE GUATEMALA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "BEETREX, S.A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BEPSA", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "BG", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BIOFARM, S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BLUE COMET LOGISTICS", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "BLUE CORPORATION", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BLUE FUSION", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BLUE VISION TECHNOLOGIES, S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BLUENET GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BLUVISION", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BOWPI", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "BSC", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "BUSINESS AS UNUSUAL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "BYTE", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "C.A CONSULTORES S.A", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "C&S LOGÍSTICA", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "C807", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "C807 OPERADOR LOGISTICO", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "CAG", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "CAIC", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "CALAMO", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "CALVET & ASSOCIATES", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CAMARA DE COMERCIO DE GUATEMALA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "CAMARA DE CORREDORES DE BIENES RAICES DE GUATEMALA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CAMARA DE LA INDUSTRIA", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "CAMARA DE LA INDUSTRIA DE GUATEMALA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CAMARA DE MICROFINANZAS DE GUATEMALA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CAMINO SEGURO", category: "Seguros", city: "Guatemala City", department: "Guatemala" },
  { name: "CANELLA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CAPGEMINI", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CARESA", category: "Comercio y Retail", city: "Escuintla", department: "Escuintla" },
  { name: "CARGA GLOBAL, S.A", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "CBC", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "CDI", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CE", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "CELASA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "CEMENTOS PROGRESO", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "CEMPRO", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "CENTRARSE", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "CENTRO MEDICO", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "CENTRO TECNICO DE INFOTMATICA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CERTECOM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CGC", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "CHEMILCO INTERNACIONAL, S.A", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "CHIPCOM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CIA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CIBERC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CIBUS", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "CIG", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "CLARITY LAW", category: "Legal", city: "Guatemala City", department: "Guatemala" },
  { name: "CLARO", category: "Tecnología", city: "Chimaltenango", department: "Chimaltenango" },
  { name: "CLARO CENAM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CLARO GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CLEIN & EMI", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "CLOUD S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CMI", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "CMI ALIMENTOS", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "COCODRILO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CODIGO GO GROUP, S.A", category: "Tecnología", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "COFIÑO STAHL", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "COINSA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "COLEGIO CAPOUILLIRZ", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "COLEGIO CIENCIA Y ARTE", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "COLEGIO SUIZO AMERICANO", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "COLORS CITY", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "COMBEX-IM", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "COMBEXIM", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "COMUNICATION CONSULTING GROUP", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "COMNET", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "COMPU BROTHERS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "COMUNICACION ASERTIVA", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "COMUNICACION ESTRATEGICA", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "COMUNITEL, S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CONDUENT", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CONNECTA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CONSORTIUM LEGAL", category: "Legal", city: "Guatemala City", department: "Guatemala" },
  { name: "CONSULTOR", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "CONSULTOR INDEPENDIENTE", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "CONSULTORIAS EN SISTEMAS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CONSULTORIA GENERAL DE CUENTAS", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "CONTROL ACADEMICO COLEGIO", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "CONTROLES GENERALES, S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "COOPERATIVA PARROQUIAL GUADALUPANA R.L.", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CORPOAGRO DEL PASIFICO S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "CORPORACION AG", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "CORPORACION BATRES S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CORPORACION DISATEL S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CORPORACION ISC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CORPORACION LITOGRAFICA", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "CORPORACION SEFEL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "CORPORACION SEGURIDAD INTEGRAL", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "COSMETICOS LECREIRE GUATEMALA", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "COTECNA GUATEMALA", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "CPN", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "CREA DE GUATEMALA S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CREATIVIDAD", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CREATRIX", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CRG", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "CURVA BIM ARCHITECTURE", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "DAP INTERNET GT", category: "Otros", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "DATA STORAGE AND PRINTING PRODUCTS GROUP, S.A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DATAGUARD S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DATA INFO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DATASYS GROUP", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DBILLYX", category: "Otros", city: "Zacapa", department: "Zacapa" },
  { name: "DEBRAIN", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DELL TECHNOLOGIES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DELOITTE GUATEMALA", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "DEMAGUSA", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "DESARROLLADORA FUTURA", category: "Agroindustria", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "DESARROLLOS HDF", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "DESISCOM", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "DEVEL GROUP", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DEVEL SECURITY", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DIDEPRO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "DIRECCION GENERAL DE RADIODIFUSION Y TELEVISION NACIONAL", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "DISAGRO", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "DISEPRO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DISTALSA", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "DISTRIBUIDORA ALCAZAREN", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "DOOPLY", category: "Tecnología", city: "Quezaltenango", department: "Quetzaltenango" },
  { name: "DOS PUNTOS CREA S.A", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "DTSOLUTIONS S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "DUWEST", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "E911", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EC CONSULTA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ECOGAES SERVICIOS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ECOINS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ECOLOX TECH", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ECPAY", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EEE", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "EEGSA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "EFISA", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "EKO TECNOLOGIAS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EL GRAN EMIR S.A", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "EL GRUPO DIGITAL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EL ORBE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ELECTROTEK", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ELEMENTOS DIGITALES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EMI/USAC", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "EMPAGUA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "EMPAQUES SAN LUCAS S.A", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "EMPRENDIMENTO PROPIO", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "EMPRESA", category: "Agroindustria", city: "Peten", department: null },
  { name: "EMPRESA ELECTRICA DE GUATEMALA", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "EN FORMACION", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "ENERGUATE", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "ENLACES EMPRESARIALES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ENTAEH", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "EPSON", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EQUIPOS Y SERVICIOS INDUSTRIALES S.A", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "AREA CONSULTING", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "ESCAS SOLUTION", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ESCUELA BANCARIA DE GUATEMALA", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "ESI", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "ESI SCHOOL OF MANAGEMENT", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "ESINSA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ESOURCE CAPITAL GUATEMALA", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "ESPATII", category: "Tecnología", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "ESPORANGIO", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ESTRATEGO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ESTRATEGO S.A", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "ESTUDIANTE", category: "Banca y Finanzas", city: "Santa Rosa", department: "Santa Rosa" },
  { name: "EVOLUA", category: "Bienes Raíces", city: "Guatemala City", department: "Guatemala" },
  { name: "EVOLUTIVA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EVOSYS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EXANET", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "EXPLORA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "FACINTER", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "FAFG", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "FAFIDESS", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "FARMACEUTICA", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "FERCO", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "FIDES GUATEMALA S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "FIGUEPARTES S.A.", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "FINANCIERA PROGRESO", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "FINANCIERA CREDICORP  S.A", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "FINANCIERA PROGRESO S.A", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "FINCA GUATEMALA", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "FOREMOSTCO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "FORTINET", category: "Ciberseguridad", city: "Guatemala City", department: "Guatemala" },
  { name: "FORZA", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "FOSFORERA CENTROAMERICANA", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "FREELANCER", category: "Marketing y Comunicación", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "FRIELY CREATIVA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "FRUTI-VER", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "FUNDACION VISION MUNDIAL GUATEMALA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "FUNDAP", category: "Otros", city: "Quezaltenango", department: "Quetzaltenango" },
  { name: "FUNDESA", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "FUSIONES ALIMENTICIAS S.A", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "GAUSS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GB", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "GBM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GEO PRODUCCIONES S.A", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GEORGE TECHNOLOGY", category: "Tecnología", city: "Retalhuleu", department: "Retalhuleu" },
  { name: "GIRO CREATIVIDAD", category: "Marketing y Comunicación", city: "Zacapa", department: "Zacapa" },
  { name: "GLOBAL MOBILITY APEX", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GMCM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GOAUTO", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "GOBOX", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "GOOD COMPANY S.A", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GP EXCELENCIA", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "GRAFITO BRANDING", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "GRANJAZUL", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "GRANT THORNTON DE GUATEMALA", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "GRECABLE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GREENS BY ESPARRAGUS", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO MACRO", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO BABEL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO BARCODE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO CESA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO CORCOM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO COSMETICO GLOBAL S.A", category: "Agroindustria", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "GRUPO CYS", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO DE TIENDAS ASOCIADAS", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO DEINCO", category: "Bienes Raíces", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO DISTELSA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO DUWEST", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO EE, S.A.", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO EJE", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO EMPRESARIAL MAMPA S.A", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO HAME", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO HEFESTOS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO HELVETICA", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO EMPERIAL", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO MASTER", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO MEGABYTE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO MENARINI", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO MONGE", category: "Comercio y Retail", city: "Baja Verapaz", department: "Baja Verapaz" },
  { name: "GRUPO PBS GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO PIT", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO PRECON", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO RAF DE GUATEMALA, S.A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO SION", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO SOLEIL", category: "Hotelería y Turismo", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO SONIX", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO TERRA", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO TRT", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPO UMA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPOAJE", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPOBA BARCODE S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "GRUPOPIT", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "GS1 GUATEMALA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GSP", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "GSPCORP", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GTM GUATEMALA COMERCIO DE PRODUCTOS QUIMICOS S.A", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "GUATEABOGADOS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "GUATEMALA FIRE S.A", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "HERBERTH ESTRADA Y ASOCIADOS GRUPO INMOBILIARIO", category: "Bienes Raíces", city: "Guatemala City", department: "Guatemala" },
  { name: "HERRAMIENTAS, MATERIALES Y EQUIPOS, S.A", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "HILOS ESPECIALIZADOS S.A", category: "Mantenimiento", city: "Quezaltenango", department: "Quetzaltenango" },
  { name: "HONDA GUATEMALA", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "HOSPITAL PILAR", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "HOSPITAL UNIVERSITARIO ESPERANZA", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "HUAWEI", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "HUAWEI TECHNOLOGIES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "HUGO", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "HUMAN TECHNOLOGIES", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "ICASA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "ICG", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "ICONE MARKETING", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "IDC DESARROLLO INMOBILIARIO, S.A.", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "IDH CONSULTING S.A", category: "Consultoría", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "IDS DE CENTROAMERICA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "IGSA", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "IGSS", category: "Salud", city: "Alta Verapaz", department: "Alta Verapaz" },
  { name: "ILG", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ILNEO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "IM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "IMAGENES COMPUTARIZADAS DE GUATEMALA", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "IMPELSA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "IMPO-EX", category: "Otros", city: "San Marcos", department: null },
  { name: "IMSA", category: "Agroindustria", city: "Escuintla", department: "Escuintla" },
  { name: "INDE", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "INDEPENDIENTE", category: "Hotelería y Turismo", city: "Guatemala City", department: "Guatemala" },
  { name: "INDIVIDUAL", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "INDUSA", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "INDUSTRIAS ODI S.A", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "INFASA", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "INGECOM", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "INGENIERIA AVANZADA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "INGENIERO MAGDALENA", category: "Agroindustria", city: "Escuintla", department: "Escuintla" },
  { name: "INGENIERO NETWORKS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "INGRUP", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "INHOUSE", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "INNOVA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "INNOVATECK", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "INNOVATION", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "INSTALACIONES MODERNAS S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "INSTITUTO AUSTRIATICO GUATEMALA", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "INTCOMEX", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "INTCOMEX DE GUATEMALA S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "INTECAP", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "INTEGRA", category: "SAP", city: "Guatemala City", department: "Guatemala" },
  { name: "INTEGRACION DE INFORMACION, S.A", category: "SAP", city: "Guatemala City", department: "Guatemala" },
  { name: "INTERBANCO", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "INTERFON", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "INVERCIONES CENTROAMERICANAS S.A", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "IRCTEC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ISERTEC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ISONET", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ISP SOLUTIONS S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "IT CONSULTING LATAM, S.A.", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "IT LEAD SERVICES", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "IT LOGICIEL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ITC CONSULTING", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "ITS INFOCOM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "IUNGO", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "JAGUAR ENERGY GUATEMALA LLC", category: "Energía", city: "Guatemala City", department: "Guatemala" },
  { name: "JAMCO", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "JCDECAUX GUATEMALA SA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "JEFE DE DESARROLLO DE SISTEMAS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "KIO NETWORKS", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "KOLEM ESTUDIO DE ARQUITECTURA", category: "Construcción", city: "Quezaltenango", department: "Quetzaltenango" },
  { name: "KPMG", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "KUEHNE+NAGEL", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "LA CONVENCIONAL S.A", category: "Alimentos", city: "Huehuetenango", department: null },
  { name: "LA PANADERIA S.A", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "LA PREPARATORIA", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "LABORATORIOS LAMFE", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "LAFLEUR", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "LAN SOLUCIONES", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "LANDO HOUSE", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "LATAM BTS S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "LAVISH SOLUTIONS", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "LETERANGO", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "LF", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "LIBRERIA EL JOCOTILLO", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "LIKASTA PUBLICIDAD", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "LIMANTO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "LINK4", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "LITHO IMPRESIONES", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "LITOGRAFIA DE OCCIDENTE", category: "Marketing y Comunicación", city: "Quezaltenango", department: "Quetzaltenango" },
  { name: "LIZTEX", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "LOGISS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "LOPLINE MARKETING", category: "Marketing y Comunicación", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "M&A CONSULTORES", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "MALHER", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "MANPOWER", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "MARKET LOGIC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "MAS DE ESTRATEGO", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "MASH", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "MASSCHALLENGE MEXICO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "MASTERCARD", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "MAXA", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "MAYUR, S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "MC2", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "MCAFEE", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "MACDONALDS", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "ME", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "MEDICABIEN", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "MEGABYTE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "MEGAPLST", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "MEGAPRINT", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "MEGAPRODUCTOS S.A", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "MERCADOS GT", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "MERCAPUBLICA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "MERCHANDISING", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "METRICA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "MEXICHEM/WAVIN", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "MIBOLSILLO APP", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "MICOOPE", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "MICROFINANZAS Y MAS", category: "Otros", city: "Quiche", department: null },
  { name: "MICROPLAST S.A", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "MINISTERIO DE DESARROLLO SOCIAL", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "MINISTERIO DE FINANZAS PUBLICAS", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "MINISTERIO DE GOBERNACION", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "MIT", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "MODUS  VIVENDI", category: "Bienes Raíces", city: "Guatemala City", department: "Guatemala" },
  { name: "MONEDAS ELECTRONICAS S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "MOTORES HINO DE GUATEMALA", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "MOVILIDAD DE TRASPORTES DE GUATEMALA", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "MT2005 S.A.", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "MUJER DE NEGOCIOS", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "MULTIEVENTOS Y VIAJES CORPORATIVOS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "MULTIPERFILES", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "MULTIPROYECTOS", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "MUNICIPALIDAD DE GUATEMALA", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "MUNICIPALIDAD DE MIXCO", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "MUNIGUATE", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "MVC", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "MYAPPSOFTWARE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "MYP", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "NA", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "NAT", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "NATURACEITES S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "NETCASTLE", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "NEXT LEVEL STRATEGY", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "NINGUNA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "NO APLICA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "NONE", category: "Tecnología", city: "Quezaltenango", department: "Quetzaltenango" },
  { name: "NOVEX, S.A", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "NUTRIRECIPIENTES S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "NWCS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "OCREPA", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "OEES", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "OFG", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "OFICINA DE MANTENIMIENTO ,PRODUCTOS Y SERVICIOS S.A", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "OFICINA PAIZ", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "OHCHR", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "ONE SOLUTION", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ONICE S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ORGANIZMO JUDICIAL", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "ORGANISMO LEGISLATIVO", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "OSI DE GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PANDA EXPRESS", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "PANI-FRESH, S.A.", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "PARTICULAR", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "PASTEUR", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "PAYNEXUS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PBS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PBS DE GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PBS GROUP", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PBS GROUP GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PBS GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PEOPLE LINK", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "PERSONAL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PFIZER", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "PIENSA SOLUCIONES", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "PINALSA S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "PIVOT", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "PIXTING", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PLASTICINA BPL", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "PLASTICOS AGRO INDUSTRIALES, S.A (PAISA)", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "PLUG AND PLAY", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PLUS HOLDING", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PM CORPORACION S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PNC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PNC GUATEMALA", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "POLICIA NACIONAL CIVIL", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "POLYPRODUCTOS DE GUATEMALA S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "POSPAN GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PR&COM", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "PRESENT", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "PREVENKIT", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "PRICESMART GUATEMALA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "PRIVADA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PROA MARKETING & IT", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "PROACTIVOS AGENCIAS DE COMUNICACION", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "PROAVISA", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "PROCESADORA DE TARGETA DE CREDITO", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "PRODUCTIVE BUSINESS SOLUTIONS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PRODUCOS AVICOLAS S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "PRODUCTIOS DEL AIRE", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "PROFECIONAL", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "PROFESOR UFM", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "PROFIL", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "PROMOAGRO", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "PROPIA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "PROSERPI", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "PROYECTOS Y REDES S.A", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "PST", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "PTAERO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "PUCHICA U+A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "QIL+4 ABOGADOS", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "QUALA CENTROAMERICA", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "QUISGT", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "R.R. DONNELLEY DE GUATEMALA. S.A.", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "REALIZE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "RECREA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "RECREA GUATE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "RECSA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "RED DE COMUNICACION INTEGRAL", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "REDECOM", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "RELACIONES INDUSTRIALES S.A", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "RENOVA", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "RENTA AUTOS DE GUATEMALA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "REPTILE:COM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "RESILIRE S.A", category: "Marketing y Comunicación", city: "Guatemala City", department: "Guatemala" },
  { name: "REVTEC", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "RICOH", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "RICOH DE GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "RICOH DE GUATEMALA S.A.", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "RICOH DE GUATEMALA, S.A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "ROCHE", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "ROYAL PRODUCE, S. A.", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "RR DONNELLEY DE GUATEMALA, S.A.", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "RUBIK", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SAF", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "SAGASTUME.BIZ", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "SANOFI", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "SAR LATAM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SAR LATIN AMERICA, S. A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SARLATAM", category: "Alimentos", city: "Guatemala City", department: "Guatemala" },
  { name: "SAS PRODUCTOS, S.A.", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "SASA", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "SAT", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "SCANSOURSE", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SCATELCORP", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SCUBE S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SEFISA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SEGEPLAN", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "SEGUROS UNIVERSALES", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "SEMIAGRO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "SENACYT", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "SEÑOR TENDERO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SERVICIO GRAFICO ALINER", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "SERVICIOS INTEGRADOS ATA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "SERVICIOS PROFECIONALES JUATA", category: "Hotelería y Turismo", city: "Quezaltenango", department: "Quetzaltenango" },
  { name: "SERVICIOS PROFECIONALES SURIKATOS", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "SERVICIOS QUIRURGICOS", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "SERVICIOS QUIRURGICOS S.A", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "SERVICIOS Y ACCESORIOS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SERVICOMP DE GUATEMALA", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "SESPRO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SETECA", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "SHIPPING LOGISTICS, S.  A.", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "SIB", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "SIDIFSA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SIECA", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "SIFCO, S.A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SIGEL", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "SIGNO DE CENTROAMERICA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SIKA GUATEMALA S.A", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "SILCOM", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "SINTEGRA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SISTEMAS EFICIENTES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SISTEMAS GTEK", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SISTEMAS, ADMINISTRACION Y FINANZAS S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SISTEMS GTEK", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SKKU", category: "Comercio y Retail", city: "Quezaltenango", department: "Quetzaltenango" },
  { name: "SKYNET VISION S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SLX", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SMART OFFICE SOLUTIONS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SMART TECH", category: "Tecnología", city: "Baja Verapaz", department: "Baja Verapaz" },
  { name: "SMARTKETING", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "SMA VENTURES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SMS VENTURES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SNACKS LU", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "SOFTLAND GUATEMALA S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SOFTWARE EN LA NUBE SALMO!, S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "SOLTEC S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SOLUCIONES ABACUS", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "SOLUCIONES ABIERTAS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "SOLUCIONES ARQUITECTONICAS", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "SOLUCIONES CUMJI", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SOLUCIONES SEGURAS", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "SOLUCIONES SEGURAS GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SOLUTIONS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "SOMIT CORREDORES DE SEGUROS", category: "Seguros", city: "Guatemala City", department: "Guatemala" },
  { name: "SOPORTE DE SERVICIOS S.A", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "SPC INTERNACIONAL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SPC INTERNATIONAL S.A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SPECTRUM", category: "Bienes Raíces", city: "Guatemala City", department: "Guatemala" },
  { name: "SRV DIGITAL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SSASA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "STG", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "STW VALVERT, S.A.", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "SUPER VITAMINAS S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "SUPERACION GALILEO", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "SUR DESARROLLOS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "SYSESA", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "T-MOBILE", category: "Tecnología", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "TARGETAS DE CREDITO DE OCCIDENTE", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "TAS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TATI", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "TECNISEGUROS", category: "Seguros", city: "Guatemala City", department: "Guatemala" },
  { name: "TECNOAVANCES", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TECNOLOGIA EXTREMA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TECNOLOGIA TRANSACCIONAL S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TECNOLOGIA Y SISTEMAS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TECNOLOGIK", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "TECNOLOGIK S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TECNSA GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TECUN", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "TELETECHNO", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "TELUS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TELUS INTERNACIONAL", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TENTONEANDO", category: "Tecnología", city: "Alta Verapaz", department: "Alta Verapaz" },
  { name: "TIANGUIS DISEÑOS", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "TIENDA MASS", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "TIENDA MASS FRANQUICIAS", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "TIGO", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TIGO / COMCEL", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "TIGO BUSINESS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TIGO GT", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TIGO GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TLF", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TODOARTE", category: "Otros", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "TOTAL MEDIA GUATEMALA", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "TPS OPERACIONES DE GUATEMALA", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "TRASPORTADORA DE ENERGIA DE GUATEMALA S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "TRUST SYSTEMS", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "TYMSA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "UFINET", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "UFINET GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "UFM", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "UMBRAL", category: "Transporte", city: "Guatemala City", department: "Guatemala" },
  { name: "UMG", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "UNIS", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "UNISEL", category: "Consultoría", city: "Guatemala City", department: "Guatemala" },
  { name: "UNISUPER", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "UNIVERSALES", category: "Banca y Finanzas", city: "Guatemala City", department: "Guatemala" },
  { name: "UNIVERSAIDAD SAN CARLOS DE GUATEMALA", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "UNIVERSIDAD DEL ITSMO", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "UNIVERSIDAD DEL VALLE DE GUATEMALA", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "UNIVERSIDAD GALILEO", category: "Educación", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "UNIVERSIDAD MARIANO GALVEZ DE GUATEMALA", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "UNIVERSIDAD RAFAEL LANDIVAR", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "URL", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "URNEXPORT", category: "Agroindustria", city: "Sacatepequez", department: "Sacatepequez" },
  { name: "USAC", category: "Educación", city: "Guatemala City", department: "Guatemala" },
  { name: "USAC-CUNOR", category: "Educación", city: "Alta Verapaz", department: "Alta Verapaz" },
  { name: "UVG", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "VAS", category: "Construcción", city: "Guatemala City", department: "Guatemala" },
  { name: "VIA ASESORES, S. A.", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "VICEPRESIDENCIA DE GUATEMALA", category: "Gobierno", city: "Guatemala City", department: "Guatemala" },
  { name: "VICKTEMP", category: "Salud", city: "Guatemala City", department: "Guatemala" },
  { name: "VIDRIOS Y MAS", category: "Automotriz", city: "Guatemala City", department: "Guatemala" },
  { name: "VIRTUAL.COM.GT", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "VISION", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "VITA&MAS", category: "Comercio y Retail", city: "Guatemala City", department: "Guatemala" },
  { name: "VITATRAC", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "VITRALUX", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "VIVIBANCO S.A", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "VOSMEDIA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "VXI", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "WALMART", category: "Otros", city: "Alta Verapaz", department: "Alta Verapaz" },
  { name: "WELLCO", category: "Mantenimiento", city: "Guatemala City", department: "Guatemala" },
  { name: "WELLCO CORPORATION, S.A", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "WESTERN UNION", category: "Otros", city: "Guatemala City", department: "Guatemala" },
  { name: "WIDOOK", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "WIT", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "WORLD VISION GUATEMALA", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "WWW.COMNETSA.COM", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
  { name: "YO MEDICOGT", category: "Agroindustria", city: "Guatemala City", department: "Guatemala" },
  { name: "ZETTABYTE S.A", category: "Tecnología", city: "Guatemala City", department: "Guatemala" },
];

async function main() {
  let created = 0, skipped = 0;
  for (const row of COMPANIES) {
    const existing = await prisma.organization.findFirst({ where: { name: row.name } });
    if (existing) { skipped++; continue; }
    await prisma.organization.create({
      data: {
        name: row.name,
        type: "SUPPLIER",
        city: row.city,
        categories: [row.category],
        mainCategory: row.category,
        coverageCity: row.city,
        coverageDepartment: row.department,
        coverageNational: false,
        isPremium: false,
        verified: false,
        active: true,
      },
    });
    created++;
  }
  console.log(`Carga terminada: ${created} empresas creadas, ${skipped} ya existían.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });