import { PrismaClient } from "@prisma/client";

/**
 * Re-clasificación manual de las 720 empresas del bootstrap inicial.
 * Cada empresa fue evaluada individualmente por contexto real (nombre +
 * dominio + sector reportado + roles observados) para asignarle una
 * categoría de BidMe más precisa que la que dieron las reglas automáticas.
 *
 * Idempotente: actualiza mainCategory y categories[] al valor correcto,
 * sin importar el valor previo. Correr de nuevo no genera efectos.
 */

const prisma = new PrismaClient();

const RECLASSIFICATION: Record<string, string> = {
  "4TO VICEMINISTERIO DE GOBERNACION": "Gobierno",
  "7TIMES": "Consultoría",
  "A.MELVILLE": "Tecnología",
  "AATECHNOLOGY": "Tecnología",
  "ABBOTT LABORATORIOS": "Salud",
  "ABC ALPHA": "Consultoría",
  "ABG": "Educación",
  "AC TALENTOS": "Consultoría",
  "ACEROS ARQUITECTONICOS": "Construcción",
  "ACEROS DE GUATEMALA": "Construcción",
  "ACOSA GUATEMALA": "Comercio y Retail",
  "ADISTEC": "Tecnología",
  "ADISTTEC": "Tecnología",
  "AFRA SERVICES": "Tecnología",
  "AFTERNOON CAFE": "Hotelería y Turismo",
  "AGEXPORT": "Comercio y Retail",
  "AGROAMERICA": "Agroindustria",
  "AKROS TECHNOLOGIES": "Tecnología",
  "ALCSA": "Alimentos",
  "ALDO SIBRIAN": "Consultoría",
  "ALEGALIS": "Legal",
  "ALFA COMUNICACIONES Y SERVICIOS": "Tecnología",
  "ALIMENTOS CORPORATIVOS CORALSA S.A": "Alimentos",
  "ALKEMY S.A": "Tecnología",
  "ALLMONI": "Marketing y Comunicación",
  "ALMACENES Y SERVICIOS, S.A": "Comercio y Retail",
  "ALMO": "Agroindustria",
  "ALOPSA": "Transporte",
  "ALPISTORE": "Comercio y Retail",
  "ALSICORP GT": "Comercio y Retail",
  "ALTEC": "Tecnología",
  "AMADEUS": "Tecnología",
  "AMCHAM GUATEMALA": "Consultoría",
  "AMPLIOS MERCADOS": "Tecnología",
  "AMTEK CENTROAMERICA, S.A.": "Automotriz",
  "AMVA": "Consultoría",
  "ANALYTECTS": "Tecnología",
  "ANFLO": "Otros",
  "ANTILLON": "Tecnología",
  "APDE ROBLE": "Educación",
  "APDE SOLALTO": "Educación",
  "APEX": "Consultoría",
  "APEX (CBC)": "Alimentos",
  "APM TERMINALS": "Transporte",
  "APMTERMINALS QUETZAL S.A.": "Transporte",
  "APOLO": "Bienes Raíces",
  "APPGATE": "Ciberseguridad",
  "APPLIS GT": "Tecnología",
  "APPSYSTEMS": "Tecnología",
  "ARCESA": "Banca y Finanzas",
  "ARCHIPEL SYSTEMS": "Tecnología",
  "AREA CONSULTING": "Consultoría",
  "ARISTA": "Tecnología",
  "ARMESA": "Agroindustria",
  "ARROCESA LOS CORRALES, S.A": "Alimentos",
  "ASEDBIEN": "Hotelería y Turismo",
  "ASEGURADORA GENERAL S.A": "Seguros",
  "ASEGURO": "Seguros",
  "ASEGURO AGENCIA DE SEGUROS, S.A": "Seguros",
  "ASEGUROS S.A.": "Seguros",
  "ASESOR LEGAL Y FINANCIERO": "Consultoría",
  "ASI ASISTENCIA INTERNACIONAL, S.A": "Seguros",
  "ASIESTRATEGIAS": "Consultoría",
  "ASIM": "Automotriz",
  "ASOCIACION EDUCATIVA ELIM": "Educación",
  "ASOCIACION ESPAÑOLA DE BENEFICIENCIA": "Salud",
  "ASOCIACION FINTECH DE GUATEMALA": "Banca y Finanzas",
  "ASTTEM": "Consultoría",
  "ATA": "Comercio y Retail",
  "ATELIER TALLER DE ESPACIOS": "Construcción",
  "ATENTO": "Consultoría",
  "AUTOMONO": "Automotriz",
  "AVAYA": "Tecnología",
  "AW": "Automotriz",
  "AXENTO": "Tecnología",
  "B&R INGENIERIA DE SISTEMAS, S. A.": "Tecnología",
  "BAC": "Banca y Finanzas",
  "BAM": "Banca y Finanzas",
  "BANCO DE GUATEMALA": "Banca y Finanzas",
  "BANCO DE LOS TRABAJADORES": "Banca y Finanzas",
  "BANCO G&T": "Banca y Finanzas",
  "BANCO G&T CONTINENTAL": "Banca y Finanzas",
  "BANCO INDUSTRIAL": "Banca y Finanzas",
  "BANCO INMOBILIARIO": "Banca y Finanzas",
  "BANCO PROMERICA": "Banca y Finanzas",
  "BANRURAL": "Banca y Finanzas",
  "BANTRAB": "Banca y Finanzas",
  "BARCELO HOTEL GROUP": "Hotelería y Turismo",
  "BBDO": "Marketing y Comunicación",
  "BC CONSULTING, S.A": "Consultoría",
  "BDG": "Consultoría",
  "BEAUTY LINE GUATEMALA": "Comercio y Retail",
  "BEETREX, S.A.": "Tecnología",
  "BEPSA": "Alimentos",
  "BG": "Banca y Finanzas",
  "BIOFARM, S.A": "Salud",
  "BLUE COMET LOGISTICS": "Transporte",
  "BLUE CORPORATION": "Tecnología",
  "BLUE FUSION": "Tecnología",
  "BLUE VISION TECHNOLOGIES, S.A": "Tecnología",
  "BLUENET GUATEMALA": "Tecnología",
  "BLUVISION": "Tecnología",
  "BOWPI": "Tecnología",
  "BSC": "Consultoría",
  "BUSINESS AS UNUSUAL": "Consultoría",
  "BYTE": "Tecnología",
  "C&S LOGÍSTICA": "Transporte",
  "C.A CONSULTORES S.A": "Consultoría",
  "C807": "Transporte",
  "C807 OPERADOR LOGISTICO": "Transporte",
  "CAG": "Educación",
  "CAIC": "Educación",
  "CALAMO": "Marketing y Comunicación",
  "CALVET & ASSOCIATES": "Consultoría",
  "CAMARA DE COMERCIO DE GUATEMALA": "Consultoría",
  "CAMARA DE CORREDORES DE BIENES RAICES DE GUATEMALA": "Bienes Raíces",
  "CAMARA DE LA INDUSTRIA": "Consultoría",
  "CAMARA DE LA INDUSTRIA DE GUATEMALA": "Consultoría",
  "CAMARA DE MICROFINANZAS DE GUATEMALA": "Banca y Finanzas",
  "CAMINO SEGURO": "Educación",
  "CANELLA": "Tecnología",
  "CAPGEMINI": "Consultoría",
  "CARESA": "Comercio y Retail",
  "CARGA GLOBAL, S.A": "Transporte",
  "CBC": "Alimentos",
  "CDI": "Tecnología",
  "CE": "Marketing y Comunicación",
  "CELASA": "Comercio y Retail",
  "CEMENTOS PROGRESO": "Construcción",
  "CEMPRO": "Construcción",
  "CENTRARSE": "Consultoría",
  "CENTRO MEDICO": "Salud",
  "CENTRO TECNICO DE INFOTMATICA": "Tecnología",
  "CERTECOM": "Tecnología",
  "CGC": "Construcción",
  "CHEMILCO INTERNACIONAL, S.A": "Salud",
  "CHIPCOM": "Tecnología",
  "CIA": "Tecnología",
  "CIBERC": "Ciberseguridad",
  "CIBUS": "Alimentos",
  "CIG": "Consultoría",
  "CLARITY LAW": "Legal",
  "CLARO": "Tecnología",
  "CLARO CENAM": "Tecnología",
  "CLARO GUATEMALA": "Tecnología",
  "CLEIN & EMI": "Educación",
  "CLOUD S.A": "Tecnología",
  "CMI": "Alimentos",
  "CMI ALIMENTOS": "Alimentos",
  "COCODRILO": "Tecnología",
  "CODIGO GO GROUP, S.A": "Tecnología",
  "COFIÑO STAHL": "Automotriz",
  "COINSA": "Tecnología",
  "COLEGIO CAPOUILLIRZ": "Educación",
  "COLEGIO CIENCIA Y ARTE": "Educación",
  "COLEGIO SUIZO AMERICANO": "Educación",
  "COLORS CITY": "Construcción",
  "COMBEX-IM": "Transporte",
  "COMBEXIM": "Transporte",
  "COMNET": "Tecnología",
  "COMPU BROTHERS": "Tecnología",
  "COMUNICACION ASERTIVA": "Marketing y Comunicación",
  "COMUNICACION ESTRATEGICA": "Marketing y Comunicación",
  "COMUNICATION CONSULTING GROUP": "Marketing y Comunicación",
  "COMUNITEL, S.A": "Tecnología",
  "CONDUENT": "Tecnología",
  "CONNECTA": "Consultoría",
  "CONSORTIUM LEGAL": "Legal",
  "CONSULTOR": "Consultoría",
  "CONSULTOR INDEPENDIENTE": "Consultoría",
  "CONSULTORIA GENERAL DE CUENTAS": "Gobierno",
  "CONSULTORIAS EN SISTEMAS": "Tecnología",
  "CONTROL ACADEMICO COLEGIO": "Educación",
  "CONTROLES GENERALES, S.A": "Alimentos",
  "COOPERATIVA PARROQUIAL GUADALUPANA R.L.": "Banca y Finanzas",
  "CORPOAGRO DEL PASIFICO S.A": "Agroindustria",
  "CORPORACION AG": "Construcción",
  "CORPORACION BATRES S.A": "Alimentos",
  "CORPORACION DISATEL S.A": "Tecnología",
  "CORPORACION ISC": "Tecnología",
  "CORPORACION LITOGRAFICA": "Comercio y Retail",
  "CORPORACION SEFEL": "Tecnología",
  "CORPORACION SEGURIDAD INTEGRAL": "Seguridad",
  "COSMETICOS LECREIRE GUATEMALA": "Comercio y Retail",
  "COTECNA GUATEMALA": "Consultoría",
  "CPN": "Gobierno",
  "CREA DE GUATEMALA S.A": "Consultoría",
  "CREATIVIDAD": "Marketing y Comunicación",
  "CREATRIX": "Tecnología",
  "CRG": "Consultoría",
  "CURVA BIM ARCHITECTURE": "Construcción",
  "DAP INTERNET GT": "Tecnología",
  "DATA INFO": "Tecnología",
  "DATA STORAGE AND PRINTING PRODUCTS GROUP, S.A.": "Tecnología",
  "DATAGUARD S.A": "Ciberseguridad",
  "DATASYS GROUP": "Tecnología",
  "DBILLYX": "Otros",
  "DEBRAIN": "Tecnología",
  "DELL TECHNOLOGIES": "Tecnología",
  "DELOITTE GUATEMALA": "Consultoría",
  "DEMAGUSA": "Alimentos",
  "DESARROLLADORA FUTURA": "Bienes Raíces",
  "DESARROLLOS HDF": "Bienes Raíces",
  "DESISCOM": "Consultoría",
  "DEVEL GROUP": "Tecnología",
  "DEVEL SECURITY": "Ciberseguridad",
  "DIDEPRO": "Otros",
  "DIRECCION GENERAL DE RADIODIFUSION Y TELEVISION NACIONAL": "Gobierno",
  "DISAGRO": "Agroindustria",
  "DISEPRO": "Tecnología",
  "DISTALSA": "Automotriz",
  "DISTRIBUIDORA ALCAZAREN": "Comercio y Retail",
  "DOOPLY": "Tecnología",
  "DOS PUNTOS CREA S.A": "Marketing y Comunicación",
  "DTSOLUTIONS S.A": "Tecnología",
  "DUWEST": "Agroindustria",
  "E911": "Tecnología",
  "EC CONSULTA": "Consultoría",
  "ECOGAES SERVICIOS": "Energía",
  "ECOINS": "Otros",
  "ECOLOX TECH": "Salud",
  "ECPAY": "Tecnología",
  "EEE": "Otros",
  "EEGSA": "Energía",
  "EFISA": "Construcción",
  "EKO TECNOLOGIAS": "Tecnología",
  "EL GRAN EMIR S.A": "Educación",
  "EL GRUPO DIGITAL": "Marketing y Comunicación",
  "EL ORBE": "Tecnología",
  "ELECTROTEK": "Tecnología",
  "ELEMENTOS DIGITALES": "Tecnología",
  "EMI/USAC": "Educación",
  "EMPAGUA": "Gobierno",
  "EMPAQUES SAN LUCAS S.A": "Comercio y Retail",
  "EMPRENDIMENTO PROPIO": "Marketing y Comunicación",
  "EMPRESA": "Otros",
  "EMPRESA ELECTRICA DE GUATEMALA": "Energía",
  "EN FORMACION": "Consultoría",
  "ENERGUATE": "Energía",
  "ENLACES EMPRESARIALES": "Consultoría",
  "ENTAEH": "Consultoría",
  "EPSON": "Tecnología",
  "EQUIPOS Y SERVICIOS INDUSTRIALES S.A": "Mantenimiento",
  "ESCAS SOLUTION": "Consultoría",
  "ESCUELA BANCARIA DE GUATEMALA": "Educación",
  "ESI": "Educación",
  "ESI SCHOOL OF MANAGEMENT": "Educación",
  "ESINSA": "Mantenimiento",
  "ESOURCE CAPITAL GUATEMALA": "Consultoría",
  "ESPATII": "Tecnología",
  "ESPORANGIO": "Agroindustria",
  "ESTRATEGO": "Marketing y Comunicación",
  "ESTRATEGO S.A": "Marketing y Comunicación",
  "ESTUDIANTE": "Otros",
  "EVOLUA": "Bienes Raíces",
  "EVOLUTIVA": "Tecnología",
  "EVOSYS": "Tecnología",
  "EXANET": "Tecnología",
  "EXPLORA": "Tecnología",
  "FACINTER": "Transporte",
  "FAFG": "Otros",
  "FAFIDESS": "Banca y Finanzas",
  "FARMACEUTICA": "Salud",
  "FERCO": "Construcción",
  "FIDES GUATEMALA S.A": "Agroindustria",
  "FIGUEPARTES S.A.": "Automotriz",
  "FINANCIERA CREDICORP  S.A": "Banca y Finanzas",
  "FINANCIERA PROGRESO": "Banca y Finanzas",
  "FINANCIERA PROGRESO S.A": "Banca y Finanzas",
  "FINCA GUATEMALA": "Banca y Finanzas",
  "FOREMOSTCO": "Comercio y Retail",
  "FORTINET": "Ciberseguridad",
  "FORZA": "Transporte",
  "FOSFORERA CENTROAMERICANA": "Comercio y Retail",
  "FREELANCER": "Tecnología",
  "FRIELY CREATIVA": "Marketing y Comunicación",
  "FRUTI-VER": "Agroindustria",
  "FUNDACION VISION MUNDIAL GUATEMALA": "Otros",
  "FUNDAP": "Otros",
  "FUNDESA": "Consultoría",
  "FUSIONES ALIMENTICIAS S.A": "Alimentos",
  "GAUSS": "Tecnología",
  "GB": "Consultoría",
  "GBM": "Tecnología",
  "GEO PRODUCCIONES S.A": "Marketing y Comunicación",
  "GEORGE TECHNOLOGY": "Tecnología",
  "GIRO CREATIVIDAD": "Marketing y Comunicación",
  "GLOBAL MOBILITY APEX": "Tecnología",
  "GMCM": "Tecnología",
  "GOAUTO": "Automotriz",
  "GOBOX": "Transporte",
  "GOOD COMPANY S.A": "Consultoría",
  "GP EXCELENCIA": "Marketing y Comunicación",
  "GRAFITO BRANDING": "Marketing y Comunicación",
  "GRANJAZUL": "Alimentos",
  "GRANT THORNTON DE GUATEMALA": "Consultoría",
  "GRECABLE": "Tecnología",
  "GREENS BY ESPARRAGUS": "Alimentos",
  "GRUPO": "Otros",
  "GRUPO BABEL": "Tecnología",
  "GRUPO BARCODE": "Tecnología",
  "GRUPO CESA": "Tecnología",
  "GRUPO CORCOM": "Tecnología",
  "GRUPO COSMETICO GLOBAL S.A": "Comercio y Retail",
  "GRUPO CYS": "Consultoría",
  "GRUPO DE TIENDAS ASOCIADAS": "Comercio y Retail",
  "GRUPO DEINCO": "Bienes Raíces",
  "GRUPO DISTELSA": "Comercio y Retail",
  "GRUPO DUWEST": "Agroindustria",
  "GRUPO EE, S.A.": "Construcción",
  "GRUPO EJE": "Automotriz",
  "GRUPO EMPERIAL": "Otros",
  "GRUPO EMPRESARIAL MAMPA S.A": "Comercio y Retail",
  "GRUPO HAME": "Agroindustria",
  "GRUPO HEFESTOS": "Tecnología",
  "GRUPO HELVETICA": "Educación",
  "GRUPO MACRO": "Construcción",
  "GRUPO MASTER": "Automotriz",
  "GRUPO MEGABYTE": "Tecnología",
  "GRUPO MENARINI": "Salud",
  "GRUPO MONGE": "Comercio y Retail",
  "GRUPO PBS GUATEMALA": "Tecnología",
  "GRUPO PIT": "Alimentos",
  "GRUPO PRECON": "Construcción",
  "GRUPO RAF DE GUATEMALA, S.A.": "Tecnología",
  "GRUPO SION": "Tecnología",
  "GRUPO SOLEIL": "Hotelería y Turismo",
  "GRUPO SONIX": "Tecnología",
  "GRUPO TERRA": "Energía",
  "GRUPO TRT": "Consultoría",
  "GRUPO UMA": "Comercio y Retail",
  "GRUPOAJE": "Alimentos",
  "GRUPOBA BARCODE S.A": "Tecnología",
  "GRUPOPIT": "Alimentos",
  "GS1 GUATEMALA": "Consultoría",
  "GSP": "Otros",
  "GSPCORP": "Comercio y Retail",
  "GTM GUATEMALA COMERCIO DE PRODUCTOS QUIMICOS S.A": "Comercio y Retail",
  "GUATEABOGADOS": "Legal",
  "GUATEMALA": "Otros",
  "GUATEMALA FIRE S.A": "Seguridad",
  "HERBERTH ESTRADA Y ASOCIADOS GRUPO INMOBILIARIO": "Bienes Raíces",
  "HERRAMIENTAS, MATERIALES Y EQUIPOS, S.A": "Construcción",
  "HILOS ESPECIALIZADOS S.A": "Comercio y Retail",
  "HONDA GUATEMALA": "Automotriz",
  "HOSPITAL PILAR": "Salud",
  "HOSPITAL UNIVERSITARIO ESPERANZA": "Salud",
  "HUAWEI": "Tecnología",
  "HUAWEI TECHNOLOGIES": "Tecnología",
  "HUGO": "Transporte",
  "HUMAN TECHNOLOGIES": "Tecnología",
  "ICASA": "Alimentos",
  "ICG": "Banca y Finanzas",
  "ICONE MARKETING": "Marketing y Comunicación",
  "IDC DESARROLLO INMOBILIARIO, S.A.": "Bienes Raíces",
  "IDH CONSULTING S.A": "Consultoría",
  "IDS DE CENTROAMERICA": "Tecnología",
  "IGSA": "Alimentos",
  "IGSS": "Gobierno",
  "ILG": "Agroindustria",
  "ILNEO": "Tecnología",
  "IM": "Tecnología",
  "IMAGENES COMPUTARIZADAS DE GUATEMALA": "Tecnología",
  "IMPELSA": "Tecnología",
  "IMPO-EX": "Comercio y Retail",
  "IMSA": "Agroindustria",
  "INDE": "Energía",
  "INDEPENDIENTE": "Consultoría",
  "INDIVIDUAL": "Otros",
  "INDUSA": "Construcción",
  "INDUSTRIAS ODI S.A": "Alimentos",
  "INFASA": "Mantenimiento",
  "INGECOM": "Consultoría",
  "INGENIERIA AVANZADA": "Tecnología",
  "INGENIERO MAGDALENA": "Agroindustria",
  "INGENIERO NETWORKS": "Tecnología",
  "INGRUP": "Comercio y Retail",
  "INHOUSE": "Marketing y Comunicación",
  "INNOVA": "Consultoría",
  "INNOVATECK": "Tecnología",
  "INNOVATION": "Consultoría",
  "INSTALACIONES MODERNAS S.A": "Construcción",
  "INSTITUTO AUSTRIATICO GUATEMALA": "Educación",
  "INTCOMEX": "Tecnología",
  "INTCOMEX DE GUATEMALA S.A": "Tecnología",
  "INTECAP": "Educación",
  "INTEGRA": "SAP",
  "INTEGRACION DE INFORMACION, S.A": "SAP",
  "INTERBANCO": "Banca y Finanzas",
  "INTERFON": "Tecnología",
  "INVERCIONES CENTROAMERICANAS S.A": "Consultoría",
  "IRCTEC": "Tecnología",
  "ISERTEC": "Tecnología",
  "ISONET": "Tecnología",
  "ISP SOLUTIONS S.A": "Tecnología",
  "IT CONSULTING LATAM, S.A.": "Consultoría",
  "IT LEAD SERVICES": "Consultoría",
  "IT LOGICIEL": "Tecnología",
  "ITC CONSULTING": "Consultoría",
  "ITS INFOCOM": "Tecnología",
  "IUNGO": "Tecnología",
  "JAGUAR ENERGY GUATEMALA LLC": "Energía",
  "JAMCO": "Alimentos",
  "JCDECAUX GUATEMALA SA": "Marketing y Comunicación",
  "JEFE DE DESARROLLO DE SISTEMAS": "Tecnología",
  "KIO NETWORKS": "Tecnología",
  "KOLEM ESTUDIO DE ARQUITECTURA": "Construcción",
  "KPMG": "Consultoría",
  "KUEHNE+NAGEL": "Transporte",
  "LA CONVENCIONAL S.A": "Alimentos",
  "LA PANADERIA S.A": "Alimentos",
  "LA PREPARATORIA": "Educación",
  "LABORATORIOS LAMFE": "Salud",
  "LAFLEUR": "Otros",
  "LAN SOLUCIONES": "Tecnología",
  "LANDO HOUSE": "Consultoría",
  "LATAM BTS S.A": "Consultoría",
  "LAVISH SOLUTIONS": "Marketing y Comunicación",
  "LETERANGO": "Salud",
  "LF": "Transporte",
  "LIBRERIA EL JOCOTILLO": "Comercio y Retail",
  "LIKASTA PUBLICIDAD": "Marketing y Comunicación",
  "LIMANTO": "Tecnología",
  "LINK4": "Marketing y Comunicación",
  "LITHO IMPRESIONES": "Marketing y Comunicación",
  "LITOGRAFIA DE OCCIDENTE": "Marketing y Comunicación",
  "LIZTEX": "Comercio y Retail",
  "LOGISS": "Consultoría",
  "LOPLINE MARKETING": "Marketing y Comunicación",
  "M&A CONSULTORES": "Consultoría",
  "MACDONALDS": "Alimentos",
  "MALHER": "Alimentos",
  "MANPOWER": "Consultoría",
  "MARKET LOGIC": "Marketing y Comunicación",
  "MAS DE ESTRATEGO": "Marketing y Comunicación",
  "MASH": "Consultoría",
  "MASSCHALLENGE MEXICO": "Consultoría",
  "MASTERCARD": "Banca y Finanzas",
  "MAXA": "Comercio y Retail",
  "MAYUR, S.A": "Comercio y Retail",
  "MC2": "Consultoría",
  "MCAFEE": "Ciberseguridad",
  "ME": "Gobierno",
  "MEDICABIEN": "Salud",
  "MEGABYTE": "Tecnología",
  "MEGAPLST": "Agroindustria",
  "MEGAPRINT": "Tecnología",
  "MEGAPRODUCTOS S.A": "Construcción",
  "MERCADOS GT": "Alimentos",
  "MERCAPUBLICA": "Marketing y Comunicación",
  "MERCHANDISING": "Marketing y Comunicación",
  "METRICA": "Tecnología",
  "MEXICHEM/WAVIN": "Construcción",
  "MIBOLSILLO APP": "Banca y Finanzas",
  "MICOOPE": "Banca y Finanzas",
  "MICROFINANZAS Y MAS": "Banca y Finanzas",
  "MICROPLAST S.A": "Comercio y Retail",
  "MINISTERIO DE DESARROLLO SOCIAL": "Gobierno",
  "MINISTERIO DE FINANZAS PUBLICAS": "Gobierno",
  "MINISTERIO DE GOBERNACION": "Gobierno",
  "MIT": "Educación",
  "MODUS  VIVENDI": "Bienes Raíces",
  "MONEDAS ELECTRONICAS S.A": "Banca y Finanzas",
  "MOTORES HINO DE GUATEMALA": "Automotriz",
  "MOVILIDAD DE TRASPORTES DE GUATEMALA": "Transporte",
  "MT2005 S.A.": "Marketing y Comunicación",
  "MUJER DE NEGOCIOS": "Marketing y Comunicación",
  "MULTIEVENTOS Y VIAJES CORPORATIVOS": "Hotelería y Turismo",
  "MULTIPERFILES": "Construcción",
  "MULTIPROYECTOS": "Construcción",
  "MUNICIPALIDAD DE GUATEMALA": "Gobierno",
  "MUNICIPALIDAD DE MIXCO": "Gobierno",
  "MUNIGUATE": "Gobierno",
  "MVC": "Gobierno",
  "MYAPPSOFTWARE": "Tecnología",
  "MYP": "Marketing y Comunicación",
  "NA": "Otros",
  "NAT": "Alimentos",
  "NATURACEITES S.A": "Alimentos",
  "NETCASTLE": "Tecnología",
  "NEXT LEVEL STRATEGY": "Consultoría",
  "NINGUNA": "Otros",
  "NO APLICA": "Otros",
  "NONE": "Otros",
  "NOVEX, S.A": "Comercio y Retail",
  "NUTRIRECIPIENTES S.A": "Comercio y Retail",
  "NWCS": "Tecnología",
  "OCREPA": "Alimentos",
  "OEES": "Educación",
  "OFG": "Tecnología",
  "OFICINA DE MANTENIMIENTO ,PRODUCTOS Y SERVICIOS S.A": "Mantenimiento",
  "OFICINA PAIZ": "Consultoría",
  "OHCHR": "Gobierno",
  "ONE SOLUTION": "Tecnología",
  "ONICE S.A": "Otros",
  "ORGANISMO LEGISLATIVO": "Gobierno",
  "ORGANIZMO JUDICIAL": "Gobierno",
  "OSI DE GUATEMALA": "Tecnología",
  "PANDA EXPRESS": "Alimentos",
  "PANI-FRESH, S.A.": "Alimentos",
  "PARTICULAR": "Otros",
  "PASTEUR": "Salud",
  "PAYNEXUS": "Banca y Finanzas",
  "PBS": "Tecnología",
  "PBS DE GUATEMALA": "Tecnología",
  "PBS GROUP": "Tecnología",
  "PBS GROUP GUATEMALA": "Tecnología",
  "PBS GUATEMALA": "Tecnología",
  "PEOPLE LINK": "Consultoría",
  "PERSONAL": "Otros",
  "PFIZER": "Salud",
  "PIENSA SOLUCIONES": "Consultoría",
  "PINALSA S.A": "Otros",
  "PIVOT": "Consultoría",
  "PIXTING": "Tecnología",
  "PLASTICINA BPL": "Comercio y Retail",
  "PLASTICOS AGRO INDUSTRIALES, S.A (PAISA)": "Agroindustria",
  "PLUG AND PLAY": "Consultoría",
  "PLUS HOLDING": "Tecnología",
  "PM CORPORACION S.A": "Tecnología",
  "PNC": "Gobierno",
  "PNC GUATEMALA": "Gobierno",
  "POLICIA NACIONAL CIVIL": "Gobierno",
  "POLYPRODUCTOS DE GUATEMALA S.A": "Comercio y Retail",
  "POSPAN GUATEMALA": "Tecnología",
  "PR&COM": "Marketing y Comunicación",
  "PRESENT": "Otros",
  "PREVENKIT": "Salud",
  "PRICESMART GUATEMALA": "Comercio y Retail",
  "PRIVADA": "Otros",
  "PROA MARKETING & IT": "Consultoría",
  "PROACTIVOS AGENCIAS DE COMUNICACION": "Marketing y Comunicación",
  "PROAVISA": "Agroindustria",
  "PROCESADORA DE TARGETA DE CREDITO": "Banca y Finanzas",
  "PRODUCOS AVICOLAS S.A": "Agroindustria",
  "PRODUCTIOS DEL AIRE": "Mantenimiento",
  "PRODUCTIVE BUSINESS SOLUTIONS": "Tecnología",
  "PROFECIONAL": "Consultoría",
  "PROFESOR UFM": "Educación",
  "PROFIL": "Construcción",
  "PROMOAGRO": "Agroindustria",
  "PROPIA": "Otros",
  "PROSERPI": "Tecnología",
  "PROYECTOS Y REDES S.A": "Tecnología",
  "PST": "Otros",
  "PTAERO": "Otros",
  "PUCHICA U+A": "Marketing y Comunicación",
  "QIL+4 ABOGADOS": "Legal",
  "QUALA CENTROAMERICA": "Alimentos",
  "QUISGT": "Tecnología",
  "R.R. DONNELLEY DE GUATEMALA. S.A.": "Marketing y Comunicación",
  "REALIZE": "Tecnología",
  "RECREA": "Educación",
  "RECREA GUATE": "Educación",
  "RECSA": "Consultoría",
  "RED DE COMUNICACION INTEGRAL": "Marketing y Comunicación",
  "REDECOM": "Tecnología",
  "RELACIONES INDUSTRIALES S.A": "Comercio y Retail",
  "RENOVA": "Construcción",
  "RENTA AUTOS DE GUATEMALA": "Automotriz",
  "REPTILE:COM": "Tecnología",
  "RESILIRE S.A": "Marketing y Comunicación",
  "REVTEC": "Tecnología",
  "RICOH": "Tecnología",
  "RICOH DE GUATEMALA": "Tecnología",
  "RICOH DE GUATEMALA S.A.": "Tecnología",
  "RICOH DE GUATEMALA, S.A.": "Tecnología",
  "ROCHE": "Salud",
  "ROYAL PRODUCE, S. A.": "Agroindustria",
  "RR DONNELLEY DE GUATEMALA, S.A.": "Marketing y Comunicación",
  "RUBIK": "Tecnología",
  "SAF": "Consultoría",
  "SAGASTUME.BIZ": "Tecnología",
  "SANOFI": "Salud",
  "SAR LATAM": "Tecnología",
  "SAR LATIN AMERICA, S. A.": "Tecnología",
  "SARLATAM": "Tecnología",
  "SAS PRODUCTOS, S.A.": "Comercio y Retail",
  "SASA": "Comercio y Retail",
  "SAT": "Gobierno",
  "SCANSOURSE": "Tecnología",
  "SCATELCORP": "Tecnología",
  "SCUBE S.A": "Tecnología",
  "SEFISA": "Tecnología",
  "SEGEPLAN": "Gobierno",
  "SEGUROS UNIVERSALES": "Seguros",
  "SEMIAGRO": "Agroindustria",
  "SENACYT": "Gobierno",
  "SERVICIO GRAFICO ALINER": "Marketing y Comunicación",
  "SERVICIOS INTEGRADOS ATA": "Consultoría",
  "SERVICIOS PROFECIONALES JUATA": "Consultoría",
  "SERVICIOS PROFECIONALES SURIKATOS": "Consultoría",
  "SERVICIOS QUIRURGICOS": "Salud",
  "SERVICIOS QUIRURGICOS S.A": "Salud",
  "SERVICIOS Y ACCESORIOS": "Tecnología",
  "SERVICOMP DE GUATEMALA": "Tecnología",
  "SESPRO": "Tecnología",
  "SETECA": "Educación",
  "SEÑOR TENDERO": "Tecnología",
  "SHIPPING LOGISTICS, S.  A.": "Transporte",
  "SIB": "Gobierno",
  "SIDIFSA": "Tecnología",
  "SIECA": "Gobierno",
  "SIFCO, S.A.": "Tecnología",
  "SIGEL": "Tecnología",
  "SIGNO DE CENTROAMERICA": "Tecnología",
  "SIKA GUATEMALA S.A": "Construcción",
  "SILCOM": "Tecnología",
  "SINTEGRA": "Tecnología",
  "SISTEMAS EFICIENTES": "Tecnología",
  "SISTEMAS GTEK": "Tecnología",
  "SISTEMAS, ADMINISTRACION Y FINANZAS S.A": "Consultoría",
  "SISTEMS GTEK": "Tecnología",
  "SKKU": "Consultoría",
  "SKYNET VISION S.A": "Tecnología",
  "SLX": "Tecnología",
  "SMA VENTURES": "Tecnología",
  "SMART OFFICE SOLUTIONS": "Tecnología",
  "SMART TECH": "Tecnología",
  "SMARTKETING": "Marketing y Comunicación",
  "SMS VENTURES": "Tecnología",
  "SNACKS LU": "Alimentos",
  "SOFTLAND GUATEMALA S.A": "Tecnología",
  "SOFTWARE EN LA NUBE SALMO!, S.A": "Tecnología",
  "SOLTEC S.A": "Tecnología",
  "SOLUCIONES ABACUS": "Consultoría",
  "SOLUCIONES ABIERTAS": "Tecnología",
  "SOLUCIONES ARQUITECTONICAS": "Construcción",
  "SOLUCIONES CUMJI": "Tecnología",
  "SOLUCIONES SEGURAS": "Ciberseguridad",
  "SOLUCIONES SEGURAS GUATEMALA": "Ciberseguridad",
  "SOLUTIONS": "Consultoría",
  "SOMIT CORREDORES DE SEGUROS": "Seguros",
  "SOPORTE DE SERVICIOS S.A": "Tecnología",
  "SPC INTERNACIONAL": "Tecnología",
  "SPC INTERNATIONAL S.A.": "Tecnología",
  "SPECTRUM": "Construcción",
  "SRV DIGITAL": "Marketing y Comunicación",
  "SSASA": "Tecnología",
  "STG": "Tecnología",
  "STW VALVERT, S.A.": "Construcción",
  "SUPER VITAMINAS S.A": "Salud",
  "SUPERACION GALILEO": "Educación",
  "SUR DESARROLLOS": "Bienes Raíces",
  "SYSESA": "Tecnología",
  "T-MOBILE": "Tecnología",
  "TARGETAS DE CREDITO DE OCCIDENTE": "Banca y Finanzas",
  "TAS": "Tecnología",
  "TATI": "Otros",
  "TECNISEGUROS": "Seguros",
  "TECNOAVANCES": "Tecnología",
  "TECNOLOGIA EXTREMA": "Tecnología",
  "TECNOLOGIA TRANSACCIONAL S.A": "Tecnología",
  "TECNOLOGIA Y SISTEMAS": "Tecnología",
  "TECNOLOGIK": "Tecnología",
  "TECNOLOGIK S.A": "Tecnología",
  "TECNSA GUATEMALA": "Tecnología",
  "TECUN": "Tecnología",
  "TELETECHNO": "Tecnología",
  "TELUS": "Tecnología",
  "TELUS INTERNACIONAL": "Tecnología",
  "TENTONEANDO": "Tecnología",
  "TIANGUIS DISEÑOS": "Marketing y Comunicación",
  "TIENDA MASS": "Comercio y Retail",
  "TIENDA MASS FRANQUICIAS": "Comercio y Retail",
  "TIGO": "Tecnología",
  "TIGO / COMCEL": "Tecnología",
  "TIGO BUSINESS": "Tecnología",
  "TIGO GT": "Tecnología",
  "TIGO GUATEMALA": "Tecnología",
  "TLF": "Tecnología",
  "TODOARTE": "Marketing y Comunicación",
  "TOTAL MEDIA GUATEMALA": "Marketing y Comunicación",
  "TPS OPERACIONES DE GUATEMALA": "Tecnología",
  "TRASPORTADORA DE ENERGIA DE GUATEMALA S.A": "Energía",
  "TRUST SYSTEMS": "Tecnología",
  "TYMSA": "Tecnología",
  "UFINET": "Tecnología",
  "UFINET GUATEMALA": "Tecnología",
  "UFM": "Educación",
  "UMBRAL": "Transporte",
  "UMG": "Educación",
  "UNIS": "Educación",
  "UNISEL": "Consultoría",
  "UNISUPER": "Comercio y Retail",
  "UNIVERSAIDAD SAN CARLOS DE GUATEMALA": "Educación",
  "UNIVERSALES": "Seguros",
  "UNIVERSIDAD DEL ITSMO": "Educación",
  "UNIVERSIDAD DEL VALLE DE GUATEMALA": "Educación",
  "UNIVERSIDAD GALILEO": "Educación",
  "UNIVERSIDAD MARIANO GALVEZ DE GUATEMALA": "Educación",
  "UNIVERSIDAD RAFAEL LANDIVAR": "Educación",
  "URL": "Educación",
  "URNEXPORT": "Agroindustria",
  "USAC": "Educación",
  "USAC-CUNOR": "Educación",
  "UVG": "Educación",
  "VAS": "Construcción",
  "VIA ASESORES, S. A.": "Consultoría",
  "VICEPRESIDENCIA DE GUATEMALA": "Gobierno",
  "VICKTEMP": "Salud",
  "VIDRIOS Y MAS": "Construcción",
  "VIRTUAL.COM.GT": "Tecnología",
  "VISION": "Otros",
  "VITA&MAS": "Comercio y Retail",
  "VITATRAC": "Comercio y Retail",
  "VITRALUX": "Construcción",
  "VIVIBANCO S.A": "Banca y Finanzas",
  "VOSMEDIA": "Marketing y Comunicación",
  "VXI": "Consultoría",
  "WALMART": "Comercio y Retail",
  "WELLCO": "Comercio y Retail",
  "WELLCO CORPORATION, S.A": "Salud",
  "WESTERN UNION": "Banca y Finanzas",
  "WIDOOK": "Tecnología",
  "WIT": "Tecnología",
  "WORLD VISION GUATEMALA": "Otros",
  "WWW.COMNETSA.COM": "Tecnología",
  "YO MEDICOGT": "Salud",
  "ZETTABYTE S.A": "Tecnología",
};

async function main() {
  let updated = 0, notFound = 0;
  for (const [name, category] of Object.entries(RECLASSIFICATION)) {
    const org = await prisma.organization.findFirst({ where: { name } });
    if (!org) { notFound++; continue; }
    await prisma.organization.update({
      where: { id: org.id },
      data: { mainCategory: category, categories: [category] },
    });
    updated++;
  }
  console.log(`Reclasificación terminada: ${updated} actualizadas, ${notFound} no encontradas.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });